spring.application.name=SpringSecurity
spring.security.user.password=1234
jwt.secret=This is jwt token secretes This is jwt token secretes This is jwt token secretes This is jwt token secretes
jwt.expiry=30000